import 'package:flutter_test/flutter_test.dart';
import 'package:{{PROJECT_SNAKE}}_mobile/main.dart';

void main() {
  testWidgets('renders the generated application shell', (tester) async {
    await tester.pumpWidget(const ProductApp());

    expect(find.text('Generated by Infra9CORE'), findsOneWidget);
  });
}
