import 'package:flutter/material.dart';

void main() => runApp(const ProductApp());

class ProductApp extends StatelessWidget {
  const ProductApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    title: '{{PROJECT_NAME}}',
    home: const Scaffold(body: Center(child: Text('Generated by Infra9CORE'))),
  );
}
