import path from "node:path";
import { APP_DEFAULT_NAMES } from "./constants.js";
import { writeText } from "./files.js";

const json = (value) => JSON.stringify(value, null, 2);

function safeModuleName(projectName, suffix) {
  return `${projectName}-${suffix}`.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

async function sveltekit(root, name, projectName) {
  const app = path.join(root, "apps", name);
  await writeText(path.join(app, "package.json"), json({
    name: `@workspace/${name}`, private: true, version: "0.0.0", type: "module",
    scripts: { dev: "vite dev", build: "vite build", preview: "vite preview", check: "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json" },
    devDependencies: { "@sveltejs/adapter-node": "^5.0.0", "@sveltejs/kit": "^2.0.0", "@sveltejs/vite-plugin-svelte": "^6.0.0", svelte: "^5.0.0", "svelte-check": "^4.0.0", typescript: "^5.0.0", vite: "^7.0.0" },
  }));
  await writeText(path.join(app, "svelte.config.js"), `import adapter from "@sveltejs/adapter-node";\nimport { vitePreprocess } from "@sveltejs/vite-plugin-svelte";\n\nexport default { preprocess: vitePreprocess(), kit: { adapter: adapter() } };`);
  await writeText(path.join(app, "vite.config.ts"), `import { sveltekit } from "@sveltejs/kit/vite";\nimport { defineConfig } from "vite";\n\nexport default defineConfig({ plugins: [sveltekit()] });`);
  await writeText(path.join(app, "tsconfig.json"), json({ extends: "./.svelte-kit/tsconfig.json", compilerOptions: { allowJs: true, checkJs: true, esModuleInterop: true, forceConsistentCasingInFileNames: true, resolveJsonModule: true, skipLibCheck: true, sourceMap: true, strict: true, moduleResolution: "bundler" } }));
  await writeText(path.join(app, "src/app.html"), `<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width,initial-scale=1" />%sveltekit.head%</head><body data-sveltekit-preload-data="hover"><div style="display: contents">%sveltekit.body%</div></body></html>`);
  await writeText(path.join(app, "src/routes/+page.svelte"), `<svelte:head><title>${projectName}</title></svelte:head>\n<main><h1>${projectName}</h1><p>Generated by Infra9CORE.</p></main>`);
  await writeText(path.join(app, "src/routes/health/+server.ts"), `import { json } from "@sveltejs/kit";\n\nexport const GET = ({ request }) => json({ status: "ok", requestId: request.headers.get("x-request-id") ?? crypto.randomUUID() });`);
}

async function python(root, name, projectName) {
  const app = path.join(root, "apps", name);
  const module = name.toLowerCase().replace(/[^a-z0-9]+/g, "_");
  await writeText(path.join(app, "pyproject.toml"), `[project]\nname = "${safeModuleName(projectName, name)}"\nversion = "0.1.0"\nrequires-python = ">=3.12"\ndependencies = ["fastapi>=0.115,<1", "uvicorn[standard]>=0.34,<1"]\n\n[project.optional-dependencies]\ndev = ["pytest>=8,<9", "ruff>=0.11,<1"]\n\n[tool.pytest.ini_options]\npythonpath = ["src"]\n\n[tool.ruff]\nline-length = 100\n`);
  await writeText(path.join(app, `src/${module}/__init__.py`), "");
  await writeText(path.join(app, `src/${module}/main.py`), `from uuid import uuid4\n\nfrom fastapi import FastAPI, Request\n\napp = FastAPI(title="${projectName} API")\n\n@app.get("/health")\nasync def health(request: Request) -> dict[str, str]:\n    return {"status": "ok", "requestId": request.headers.get("x-request-id", str(uuid4()))}\n`);
  await writeText(path.join(app, "tests/test_health.py"), `from fastapi.testclient import TestClient\nfrom ${module}.main import app\n\n\ndef test_health() -> None:\n    response = TestClient(app).get("/health")\n    assert response.status_code == 200\n    assert response.json()["status"] == "ok"\n`);
}

async function go(root, name, projectName) {
  const app = path.join(root, "apps", name);
  const module = `example.invalid/${safeModuleName(projectName, name)}`;
  await writeText(path.join(app, "go.mod"), `module ${module}\n\ngo 1.24`);
  await writeText(path.join(app, "cmd/server/main.go"), `package main\n\nimport (\n  "encoding/json"\n  "log/slog"\n  "net/http"\n  "os"\n)\n\nfunc main() {\n  logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))\n  mux := http.NewServeMux()\n  mux.HandleFunc("GET /health", func(w http.ResponseWriter, r *http.Request) {\n    w.Header().Set("Content-Type", "application/json")\n    _ = json.NewEncoder(w).Encode(map[string]string{"status": "ok", "requestId": r.Header.Get("X-Request-Id")})\n  })\n  logger.Info("server_started", "address", ":8080")\n  if err := http.ListenAndServe(":8080", mux); err != nil { logger.Error("server_stopped", "error", err); os.Exit(1) }\n}\n`);
}

async function rust(root, name, projectName) {
  const app = path.join(root, "apps", name);
  await writeText(path.join(app, "Cargo.toml"), `[package]\nname = "${safeModuleName(projectName, name)}"\nversion = "0.1.0"\nedition = "2024"\n\n[dependencies]\naxum = "0.8"\nserde = { version = "1", features = ["derive"] }\ntokio = { version = "1", features = ["macros", "rt-multi-thread"] }\nuuid = { version = "1", features = ["v4"] }\n`);
  await writeText(path.join(app, "src/main.rs"), `use axum::{routing::get, Json, Router};\nuse serde::Serialize;\nuse uuid::Uuid;\n\n#[derive(Serialize)]\n#[serde(rename_all = "camelCase")]\nstruct Health { status: &'static str, request_id: Uuid }\n\n#[tokio::main]\nasync fn main() {\n    let app = Router::new().route("/health", get(|| async { Json(Health { status: "ok", request_id: Uuid::new_v4() }) }));\n    let listener = tokio::net::TcpListener::bind("0.0.0.0:8080").await.unwrap();\n    axum::serve(listener, app).await.unwrap();\n}\n`);
}

async function flutter(root, name, projectName) {
  const app = path.join(root, "apps", name);
  const packageName = safeModuleName(projectName, name).replaceAll("-", "_");
  await writeText(path.join(app, "pubspec.yaml"), `name: ${packageName}\ndescription: Product-neutral Flutter application generated by Infra9CORE.\npublish_to: none\nversion: 0.1.0+1\nenvironment:\n  sdk: ">=3.5.0 <4.0.0"\ndependencies:\n  flutter:\n    sdk: flutter\ndev_dependencies:\n  flutter_test:\n    sdk: flutter\n  flutter_lints: ^5.0.0\nflutter:\n  uses-material-design: true\n`);
  await writeText(path.join(app, "lib/main.dart"), `import 'package:flutter/material.dart';\n\nvoid main() => runApp(const ProductApp());\n\nclass ProductApp extends StatelessWidget {\n  const ProductApp({super.key});\n  @override\n  Widget build(BuildContext context) => MaterialApp(\n    title: '${projectName}',\n    home: const Scaffold(body: Center(child: Text('Generated by Infra9CORE'))),\n  );\n}\n`);
  await writeText(path.join(app, "README.md"), `# Flutter application\n\nRun \`flutter create . --project-name ${packageName}\` once to add the desired native platform runners, then run \`flutter test\`.`);
}

async function tauri(root, name, projectName) {
  const app = path.join(root, "apps", name);
  await writeText(path.join(app, "package.json"), JSON.stringify({ name: `@workspace/${name}`, private: true, version: "0.0.0", scripts: { tauri: "tauri" }, devDependencies: { "@tauri-apps/cli": "^2.0.0" } }, null, 2));
  await writeText(path.join(app, "index.html"), `<!doctype html><html lang="en"><meta charset="utf-8"><title>${projectName}</title><body><h1>${projectName}</h1><p>Generated by Infra9CORE.</p></body></html>`);
  await writeText(path.join(app, "src-tauri/Cargo.toml"), `[package]\nname = "${safeModuleName(projectName, name)}"\nversion = "0.1.0"\nedition = "2021"\n\n[build-dependencies]\ntauri-build = { version = "2", features = [] }\n\n[dependencies]\ntauri = { version = "2", features = [] }\n\n[lib]\ncrate-type = ["staticlib", "cdylib", "rlib"]\n`);
  await writeText(path.join(app, "src-tauri/build.rs"), "fn main() { tauri_build::build() }");
  await writeText(path.join(app, "src-tauri/src/lib.rs"), `#[cfg_attr(mobile, tauri::mobile_entry_point)]\npub fn run() { tauri::Builder::default().run(tauri::generate_context!()).expect("Tauri runtime failed"); }`);
  await writeText(path.join(app, "src-tauri/src/main.rs"), `fn main() { ${safeModuleName(projectName, name).replaceAll("-", "_")}::run(); }`);
  await writeText(path.join(app, "src-tauri/tauri.conf.json"), json({ $schema: "https://schema.tauri.app/config/2", productName: projectName, version: "0.1.0", identifier: `com.example.${safeModuleName(projectName, name).replaceAll("-", "")}`, build: { frontendDist: "../" }, app: { windows: [{ title: projectName, width: 1000, height: 700 }] }, bundle: { active: false } }));
  await writeText(path.join(app, "src-tauri/capabilities/default.json"), json({ identifier: "default", description: "Default desktop capability", windows: ["main"], permissions: ["core:default"] }));
}

async function custom(root, name) {
  await writeText(path.join(root, "apps", name, "README.md"), "# Custom application\n\nDocument its domain, ports, health contract, deployment artifact, and test commands before implementation.");
}

const recipes = { sveltekit, flutter, python, go, rust, tauri, custom };

export async function createApplications(root, appTypes, projectName) {
  const created = [];
  for (const type of appTypes) {
    const name = APP_DEFAULT_NAMES[type];
    await recipes[type](root, name, projectName);
    created.push({ type, name });
  }
  return created;
}
