import { parseCliArguments } from "./arguments.js";
import { collectInteractiveOptions } from "./prompt.js";
import { describePlan, generateProject, INITIAL_DEVELOPER_HANDOFF, normalizeOptions, packageVersion } from "./generator.js";
import { inspectProject } from "./project-doctor.js";
import { assertSupportedNode } from "./runtime.js";
import { emitSarvaOpsPortAllocation } from './operational-contracts.js';

const HELP = `Infra9CORE - production-minded multi-stack repository generator

Usage:
  create-infra9core [destination] [options]
  create-infra9core doctor [project-path]
  create-infra9core update [project-path] --check
  create-infra9core contract sarvaops-ports --project-number <n> --environment <production|uat|development> --output <file>

Options:
  -n, --name <name>               Project display name
  -a, --apps <list>               sveltekit,flutter,python,go,rust,tauri,custom,none
  -f, --features <list>           Optional overlays: ci or none
  -p, --package-manager <name>    pnpm, npm, yarn, or bun
      --organization-id <id>      Reverse-domain app ID (default: com.example)
      --flutter-platforms <list>  android,ios,web,linux,macos,windows
  -y, --yes                       Accept defaults; disable prompts
      --install                   Install JavaScript dependencies
      --no-git                    Do not initialize a Git repository
      --dry-run                   Print the generation plan without writing
      --force                     Allow generation into a non-empty directory
  -v, --version                   Print version
  -h, --help                      Show this help

Example:
  npx @unifyit/create-infra9core@latest my-product --apps sveltekit,flutter,python --features ci --organization-id com.example
`;

export async function run(argv) {
  assertSupportedNode();
  if (argv[0] === "doctor") {
    if (argv.length > 2) throw new Error("Doctor accepts at most one project path");
    const result = await inspectProject(argv[1] ?? ".");
    console.log(`Infra9CORE doctor: ${result.root}`);
    if (result.ok) {
      console.log(`OK: template contract ${result.manifest.templateContractVersion}, generated by ${result.manifest.generator.version}`);
      return;
    }
    for (const finding of result.findings) console.error(`- ${finding}`);
    process.exitCode = 1;
    return;
  }
  if (argv[0] === "update") {
    const args = argv.slice(1);
    const check = args.includes("--check");
    const projectPath = args.find((item) => item !== "--check") ?? ".";
    if (!check || args.filter((item) => item !== "--check").length > 1) {
      throw new Error("Update is read-only; use: create-infra9core update [project-path] --check");
    }
    const result = await inspectProject(projectPath);
    if (!result.ok) {
      console.error("Infra9CORE update check cannot plan an upgrade:");
      for (const finding of result.findings) console.error(`- ${finding}`);
      process.exitCode = 1;
      return;
    }
    const installedVersion = await packageVersion();
    const generatedVersion = result.manifest.generator.version;
    console.log(`Infra9CORE update check: ${result.root}`);
    if (generatedVersion === installedVersion) {
      console.log(`No generator version drift detected (${installedVersion}). No files were changed.`);
    } else {
      console.log(`Generated by ${generatedVersion}; installed generator is ${installedVersion}.`);
      console.log("No files were changed. Review release notes before any future managed-file update.");
    }
    return;
  }
  if (argv[0] === 'contract') {
    if (argv[1] !== 'sarvaops-ports') throw new Error('Supported contract: sarvaops-ports');
    const value = (name) => {
      const index = argv.indexOf(name);
      if (index === -1 || !argv[index + 1]) throw new Error(`Missing ${name}`);
      return argv[index + 1];
    };
    const document = await emitSarvaOpsPortAllocation({
      projectNumber: Number(value('--project-number')),
      environment: value('--environment'),
      output: value('--output'),
    });
    console.log(`Wrote ${document.contract} for project ${document.projectNumber} (${document.environment}).`);
    return;
  }
  const parsed = parseCliArguments(argv);
  if (parsed.help) { console.log(HELP); return; }
  if (parsed.version) { console.log(await packageVersion()); return; }
  const answers = await collectInteractiveOptions(parsed);
  const config = normalizeOptions(answers);
  console.log(`\n${describePlan(config)}\n`);
  const result = await generateProject(config);
  if (result.created) {
    console.log(`Infra9CORE created ${result.config.projectName} at ${result.config.destination}`);
    console.log("Review the generated ADR and environment template before starting services.");
    console.log(`\n${"=".repeat(78)}\nREQUIRED BEFORE PRODUCT IMPLEMENTATION: INITIAL CODING-AGENT HANDOFF\n${"=".repeat(78)}`);
    console.log("First run make infra9core, make env, make doctor, and make config. Then copy the prompt below into your coding agent.");
    console.log("It is also saved in README.md under ‘First developer handoff’.\n");
    console.log(INITIAL_DEVELOPER_HANDOFF);
    console.log(`${"=".repeat(78)}\n`);
  } else {
    console.log("Dry run complete; no files were written.");
  }
}
